/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package llistaPila;

import javax.swing.JOptionPane;

/**
 *
 * @author mblan
 */
public class Interfície extends javax.swing.JFrame {

    /**
     * Creates new form Interfície
     */
    public Interfície() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtExpressio.setText("{3*(7-6)-[3*7]-{6-3}}");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtExpressio = new javax.swing.JTextField();
        buttonValidarExpressio = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtExpressio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtExpressio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpressioActionPerformed(evt);
            }
        });

        buttonValidarExpressio.setText("Validar expressió");
        buttonValidarExpressio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValidarExpressioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(buttonValidarExpressio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtExpressio, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(txtExpressio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonValidarExpressio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpressioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpressioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpressioActionPerformed

    private void buttonValidarExpressioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValidarExpressioActionPerformed
        if (ValidarExpressio()) {
            JOptionPane.showMessageDialog(null, "L'espressió està escrita correctament.");
            
        } else {
            JOptionPane.showMessageDialog(null, "Error, l'expressió està mal escrita");
        }
    }//GEN-LAST:event_buttonValidarExpressioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfície.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfície.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfície.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfície.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfície().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonValidarExpressio;
    private javax.swing.JTextField txtExpressio;
    // End of variables declaration//GEN-END:variables

    public boolean ValidarExpressio() {
        PilaExercici2 pila = new PilaExercici2();
        String cadena = txtExpressio.getText();

        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.charAt(i) == '(' || cadena.charAt(i) == '{' || cadena.charAt(i) == '[') {
                pila.Introduir(cadena.charAt(i));
                System.out.println(cadena.charAt(i));

            } else {

                if (cadena.charAt(i) == ')') {

                    if (pila.Extrure() != '(') {
                        return false;
                    }

                } else {
                    if (cadena.charAt(i) == ']') {

                        if (pila.Extrure() != '[') {
                            return false;
                        }

                    } else {

                        if (cadena.charAt(i) == '}') {
                            if (pila.Extrure() != '{') {
                                return false;
                            }

                        }

                    }

                }
            }
        }
        return pila.PilaBuida();
    }
}
